### PR TITLE
MOSIP-32782 - Password-protected file is not allowed for upload

### PR DESCRIPTION
**Pull request by GOKULRAJ136**

### CODE REVIEW

**Review by mayuradesh — CHANGES_REQUESTED** [review]
Check the the error code and update err handling in file-upload.component.ts

**Comment by GOKULRAJ136** [comment]
> Check the the error code and update err handling in file-upload.component.ts

Implemented suitable error handling for password-protected files using conditional statements.

**Review by mayuradesh — CHANGES_REQUESTED** [review]
Change "=" with "==" to have comparison

**Comment by GOKULRAJ136** [comment]
> Change "=" with "==" to have comparison

added proper error handling by using  "=="

**Review by mayuradesh — APPROVED** [review]

**Pull request merged**
